### ISSUE TITLE
Cannot compile with efl 1.20.99 on FreeBDD 11

### ISSUE THREAD

**Issue by Peter2121** [marcelhollerbach/verne#30]
Trying to do 'make all' 
[ 41%] Linking C shared library libefm.so
[ 41%] Built target efm
[ 42%] Generating ../../../src/widgets/dialog/elm_dialog.eo.x
eolian: function 'part_text' not found in class 'Widget'
eolian:elm_dialog.eo:19:9: function 'part_text' not known in class 'Elm.Widget'
eolian: could not parse file '/usr/home/peter/Programming/Prog-EFL/verne/verne/src/widgets/dialog/elm_dialog.eo'
*** Error code 1

Trying to do 'gmake all' 

[ 41%] Linking C shared library libefm.so
[ 41%] Built target efm
[ 42%] Generating ../../../src/widgets/file/views/elm_file_display_view_list.eo.h
eolian:elm_file_view.eo:15:22: undefined type Eina.Rectangle
eolian: could not parse file '/usr/home/peter/Programming/Prog-EFL/verne/verne/src/widgets/file/views/elm_file_display_view_list.eo'
gmake[2]: *** [src/widgets/CMakeFiles/elm_ext.dir/build.make:8858: ../src/widgets/file/views/elm_file_display_view_list.eo.h] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:361: src/widgets/CMakeFiles/elm_ext.dir/all] Error 2
gmake: *** [Makefile:139: all] Error 2

**Comment by marcelhollerbach** [comment]
Should work now again with latest efl-git! 

Thanks for the heads up!
